[MN-1057] Validate provisioning profile list before save
bitrise-io/addons-ship-backend pull request #152
Opened 2021-02-02 13:29 UTC by slapec93

2021-02-04 08:56 UTC, zormandi requested changes

2021-02-04 08:56 UTC, zormandi commented on models/common.go
> +
I really dislike the idea of having to write this sort of functionality ourselves. I know there's no built-in support for it in the language but why don't we use some lib like https://github.com/thoas/go-funk ?

2021-02-04 08:56 UTC, zormandi commented on models/app_settings.go
> +	for _, slug := range s.SelectedAppStoreProvisioningProfiles {
This is basically an intersection operation between two slices. Again, let's use a lib for this.

2021-02-04 08:56 UTC, zormandi commented on services/app_settings_patch.go
> +			for _, provProfile := range existingProvProfiles {
This is a `map` operation. :)

2021-02-05 12:06 UTC, komaromia commented on models/app_settings.go
> +	for _, slug := range s.SelectedAppStoreProvisioningProfiles {
So this is not in the funk lib?

2021-02-05 13:20 UTC, komaromia approved these changes

2021-02-05 13:21 UTC, merged